### PR TITLE
fix(sm): Sanitize player counts

### LINKED ISSUE #72: Player count from servers should be sanitized
`serverManager/src/GameServer.js` expects the `reportPlayerCount(count)` parameter to be a number, but we should make sure it actually is. Otherwise untrusted servers might send arbitrary data and it could leak into the client

### PR DESCRIPTION
**Pull request by jespertheend**
Fixes #72

### CODE REVIEW

File: serverManager/src/GameServer.js [hunk 1]
```diff
@@ -24,6 +24,10 @@ function createResponseHandlers(gameServer) {
 		 * @param {number} count
 		 */
 		reportPlayerCount(count) {
+			if (typeof count != "number") {
```
Comment (splixcord) [inline serverManager/src/GameServer.js:27]: NaN?

File: serverManager/src/GameServer.js [hunk 2]
```diff
@@ -24,6 +24,10 @@ function createResponseHandlers(gameServer) {
...
+				count = 0;
+			}
+			count = clamp(count, 0, 999);
```
Comment (splixcord) [inline serverManager/src/GameServer.js:30]: Floats like 1.1?

**Review by splixcord — CHANGES_REQUESTED** [review]

**Review by splixcord — APPROVED** [review]
